### ISSUE TITLE
Newly generated code doesn't work on grunt serve

### ISSUE THREAD

**Issue by geekgugi** [hung-phan/generator-angular-with-browserify#2]
When invoked grunt serve on newly generated folder, browserify:app task fails 
Running "browserify:app" (browserify) task
>> Error: Cannot find module 'bootstrap' from '<%project%>/app/src'

**Comment by hung-phan** [comment]
I had a look at the problem, the quick fix would be replaced `require('bootstrap')` by `require('../bower_components/sass-bootstrap/dist/js/bootstrap')`. I will find another way to fix this issue. Thanks for report, @geekgugi
