### ISSUE TITLE
How to inject a factory into a controller

### ISSUE THREAD

**Issue by nabong04** [hung-phan/generator-angular-with-browserify#3]
Hi, I just tried this generator and it perfectly fits my needs. However, I'm very new to browserify and I'm wondering what's the way to inject a factory into a controller. Both my factory and controller have been generated with this generator? When I require a factory in the controller file and do a direct DI, it doesn't work.

```
require('angular/angular');
require('./path/to/my/factory');

angular.module('myModule', []).controller('ControllerName', ['MyFactory', function(MyFactory){
     // controller code here
}]);

```

Any help on this?

**Comment by hung-phan** [comment]
It cannot be done that way because angular uses dependencies injection. What you should do is to load it via module.

For example, 

my-factory.js

```
require('angular/angular');
module.exports = angular.module('myModule.myFactory', []).factory(.....);
```

my-module.js

```
require('angular/angular');
require('./path/to/my-factory');

angular.module('myModule', ['myModule.myFactory']).controller('ControllerName', ['MyFactory', function(MyFactory){
     // controller code here
}]);

```

**Comment by hung-phan** [comment]
Let me know if this fix your problem
